name: Mrs. Nostradamus
favicon: null
layout_spectrum: 0.06033100723288953
typography_spectrum: 0.3949087983928621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9781322069466114
  lightness: 0.27668780740350485
  saturation: 0.18564632278867066
  rhythmicContrast: 0.24814067734405398
purpose: []
